Repository coitloz88/alcohol-free, pull requests merged in 2023-03, with the labels that each got.

#14 architecture refactored
  lib/app/data/providers/firebase_auth_provider.dart
  lib/app/data/services/auth_service/auth_repository.dart
  lib/app/data/services/auth_service/auth_service.dart
  lib/core/utils/app_initializations.dart
  lib/main.dart
Labels: enhancement, task

#16 android, ios notification 위한 설정
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner/AppDelegate.swift
  lib/app/data/services/notification_service/notification_repository.dart
  lib/app/data/services/notification_service/notification_service.dart
  lib/core/utils/app_initializations.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: task

#21 fix compile error by referencing non-existent file
  lib/core/utils/app_initializations.dart
Labels: bug

#25 replace tab strings with icons and add app bar
  assets/images/logo_app_bar.png
  lib/main.dart
  lib/main_view_controller.dart
  pubspec.yaml
Labels: task

#32 add font `SUIT`
  assets/fonts/SUIT-Bold.ttf
  assets/fonts/SUIT-ExtraBold.ttf
  assets/fonts/SUIT-ExtraLight.ttf
  assets/fonts/SUIT-Heavy.ttf
  assets/fonts/SUIT-Light.ttf
  assets/fonts/SUIT-Medium.ttf
  assets/fonts/SUIT-Regular.ttf
  assets/fonts/SUIT-SemiBold.ttf
  assets/fonts/SUIT-Thin.ttf
  lib/main.dart
  pubspec.yaml
Labels: task

#38 feature/28
  lib/app/data/models/alcohol_free_user.dart
  lib/app/data/providers/firebase_auth_provider.dart
  lib/app/data/providers/firestore_provider.dart
  lib/app/data/services/auth_service/auth_service.dart
  lib/app/data/services/promise_service/promise_repository.dart
  lib/app/data/services/promise_service/promise_service.dart
  lib/app/data/services/user_service/user_repository.dart
  lib/app/data/services/user_service/user_service.dart
  lib/core/utils/app_initializations.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: task

#44 add utils that return size of widgets and screen
  lib/app/utils/screen_size.dart
  lib/app/utils/widget_layout_data.dart
Labels: task

#46 connect home and promise page
  assets/images/empty_profile.png
  assets/images/empty_profile_circle.png
  lib/app/data/enums/level_of_access.dart
  lib/app/data/models/alcohol_free_user.dart
  lib/app/data/models/consumption_based_requisite.dart
  lib/app/data/models/day_based_requisite.dart
  lib/app/data/models/progress_list_item_data.dart
  lib/app/data/models/promise.dart
  lib/app/data/models/requisite.dart
  lib/app/data/services/user_service/user_service.dart
  lib/app/modules/home/home_page.dart
  lib/app/modules/home/home_page_controller.dart
  lib/app/modules/home/local_widgets/current_promise_listitem_view.dart
  lib/app/modules/home/local_widgets/current_promise_view.dart
  lib/app/modules/home/local_widgets/profile_view.dart
  lib/app/modules/home/local_widgets/week_calendar_view.dart
  lib/app/modules/promise/local_widgets/progress_list_item.dart
  lib/app/modules/promise/local_widgets/promise_sort_option.dart
  lib/app/modules/promise/local_widgets/promise_view.dart
  lib/app/modules/promise/promise_page.dart
  lib/app/modules/promise/promise_page_controller.dart
  lib/core/languages/app_localizations.dart
  lib/core/languages/app_localizations_ko.dart
  lib/core/languages/l10n/app_ko.arb
  lib/core/utils/app_initializations.dart
  lib/main.dart
  lib/main_view_controller.dart
  pubspec.lock
  pubspec.yaml
  web/manifest.json
Labels: task

#50 implement calendar and drinking day page skeleton
  assets/images/calendar_add_drink.png
  assets/images/calendar_add_sober.png
  lib/app/modules/calendar/calendar_page.dart
  lib/app/modules/calendar/local_widgets/add_button.dart
  lib/app/modules/calendar/local_widgets/add_button_wrapper.dart
  lib/app/modules/calendar/local_widgets/month_calendar_view.dart
  lib/app/modules/drinking_journal_add/drinking_journal_page.dart
  lib/app/modules/drinking_journal_add/drinking_journal_page_controller.dart
  lib/app/modules/drinking_journal_add/local_widgets/container_with_heading.dart
  lib/app/modules/home/local_widgets/week_calendar_view.dart
  lib/app/modules/promise/promise_page.dart
  lib/app/modules/promise/promise_page_controller.dart
  lib/app/modules/sobriety_journal/sobriety_journal_page.dart
  lib/app/widgets/afree_drop_down_button.dart
  lib/app/widgets/confirm_button.dart
  lib/app/widgets/global_button_widgets.dart
  lib/app/widgets/mood_selection_row.dart
  lib/app/widgets/textbox_with_heading.dart
  lib/app/widgets/widget_with_left_heading.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, task

#67 show friend checklist UI and fix some constant values
  lib/app/data/providers/firestore_provider.dart
  lib/app/data/services/friends_service/friends_service.dart
  lib/app/modules/home/home_page.dart
  lib/app/modules/home/local_widgets/current_promise_listitem_view.dart
  lib/app/modules/home/local_widgets/current_promise_view.dart
  lib/app/modules/new_promise/local_widgets/add_friend_button.dart
  lib/app/modules/new_promise/local_widgets/available_friends_list_item.dart
  lib/app/modules/new_promise/local_widgets/data_picker.dart
  lib/app/modules/new_promise/local_widgets/friends_list_bottom_sheet.dart
  lib/app/modules/new_promise/new_promise_page.dart
  lib/app/modules/new_promise/new_promise_page_controller.dart
  lib/app/modules/promise/local_widgets/progress_list_item.dart
  lib/app/modules/promise/local_widgets/promise_list_view.dart
  lib/app/modules/promise/local_widgets/promise_tab_view.dart
  lib/app/modules/promise/promise_page.dart
  lib/app/modules/promise/promise_page_controller.dart
  lib/app/widgets/mood_selection_row.dart
Labels: bug, task

#68 journal 올리고, 보는거 완료..
  lib/app/modules/calendar/calendar_page_controller.dart
  lib/app/modules/calendar/local_widgets/month_calendar_view.dart
  lib/app/modules/drinking_journal_add/drinking_journal_page.dart
  lib/app/modules/drinking_journal_add/drinking_journal_page_controller.dart
  lib/app/modules/new_promise/local_widgets/journal_widget.dart
  lib/app/modules/new_promise/new_promise_page.dart
  lib/app/modules/sobriety_journal/local_widgets/journal_heading.dart
  lib/app/modules/sobriety_journal/sobriety_journal_page.dart
  lib/app/modules/sobriety_journal/sobriety_journal_page_controller.dart
  lib/app/widgets/afree_drop_down_button.dart
  lib/app/widgets/textbox_with_heading.dart
  lib/app/widgets/widget_with_left_heading.dart
Labels: task
